import {
  createContext,
  useContext,
  useEffect,
  useState,
} from 'react';

import api from '../api/axios.js';

const AuthContext = createContext();

const safeParse = (raw) => {
  if (!raw || raw === 'undefined' || raw === 'null') {
    return null;
  }

  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
};

export const AuthProvider = ({ children }) => {
  const [user, setUser] = useState(() =>
    safeParse(localStorage.getItem('user'))
  );

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const bootstrap = async () => {
      const token = localStorage.getItem('token');
      const storedUser = safeParse(
        localStorage.getItem('user')
      );

      console.log('========== AUTH BOOTSTRAP ==========');
      console.log('Token exists:', !!token);
      console.log('Stored user:', storedUser);
      console.log('Stored role:', storedUser?.role);

      // No token
      if (
        !token ||
        token === 'undefined' ||
        token === 'null'
      ) {
        localStorage.removeItem('token');
        localStorage.removeItem('user');

        setUser(null);
        setLoading(false);

        return;
      }

      /*
       * CLIENT SESSION
       *
       * Client token is generated by:
       * /api/client-auth/login
       *
       * Therefore we should NOT call:
       * /api/auth/me
       *
       * because that endpoint belongs to employees.
       */
      if (
        storedUser?.role &&
        String(storedUser.role).toLowerCase() === 'client'
      ) {
        console.log(
          'CLIENT SESSION FOUND - keeping client session'
        );

        setUser({
          ...storedUser,
          role: 'client',
        });

        setLoading(false);

        return;
      }

      /*
       * EMPLOYEE SESSION
       */
      try {
        console.log(
          'EMPLOYEE SESSION - checking /auth/me'
        );

        const { data } = await api.get('/auth/me');

        console.log(
          'AUTH ME RESPONSE:',
          data
        );

        if (!data?.user) {
          throw new Error(
            'Invalid user session'
          );
        }

        setUser(data.user);

        localStorage.setItem(
          'user',
          JSON.stringify(data.user)
        );
      } catch (error) {
        console.error(
          'SESSION ERROR:',
          error
        );

        localStorage.removeItem('token');
        localStorage.removeItem('user');

        setUser(null);
      } finally {
        setLoading(false);
      }
    };

    bootstrap();
  }, []);

  const login = async (
    identifier,
    password
  ) => {
    const value = String(
      identifier || ''
    ).trim();

    console.log(
      '========== LOGIN DEBUG =========='
    );

    console.log(
      'Identifier:',
      value
    );

    if (!value) {
      throw new Error(
        'Email or Client ID is required'
      );
    }

    if (!password) {
      throw new Error(
        'Password is required'
      );
    }

    let response;

    /*
     * EMAIL LOGIN
     *
     * First try CLIENT email.
     * If client email is not found,
     * try EMPLOYEE email.
     */
    if (value.includes('@')) {
      const email = value.toLowerCase();

      console.log(
        'EMAIL LOGIN'
      );

      console.log(
        'EMAIL:',
        email
      );

      try {
        console.log(
          'Trying CLIENT LOGIN first'
        );

        response = await api.post(
          '/client-auth/login',
          {
            email,
            password,
          }
        );

        console.log(
          'CLIENT LOGIN SUCCESS'
        );
      } catch (clientError) {
        console.log(
          'CLIENT LOGIN FAILED'
        );

        console.log(
          'Trying EMPLOYEE LOGIN'
        );

        response = await api.post(
          '/auth/login',
          {
            email,
            password,
          }
        );

        console.log(
          'EMPLOYEE LOGIN SUCCESS'
        );
      }
    } else {
      /*
       * CLIENT ID LOGIN
       */
      const portalId = value.toUpperCase();

      console.log(
        'CLIENT ID LOGIN'
      );

      console.log(
        'PORTAL ID:',
        portalId
      );

      response = await api.post(
        '/client-auth/login',
        {
          portalId,
          password,
        }
      );
    }

    console.log(
      'LOGIN RESPONSE:',
      response.data
    );

    const { data } = response;

    if (!data?.token) {
      throw new Error(
        data?.message ||
          'Token not received from server'
      );
    }

    if (!data?.user) {
      throw new Error(
        data?.message ||
          'User data not received from server'
      );
    }

    /*
     * Normalize client role
     */
    const normalizedUser =
      String(data.user.role).toLowerCase() ===
      'client'
        ? {
            ...data.user,
            role: 'client',
          }
        : data.user;

    console.log(
      'FINAL USER:',
      normalizedUser
    );

    console.log(
      'FINAL ROLE:',
      normalizedUser.role
    );

    /*
     * Save authentication
     */
    localStorage.setItem(
      'token',
      data.token
    );

    localStorage.setItem(
      'user',
      JSON.stringify(normalizedUser)
    );

    /*
     * Update React state
     */
    setUser(normalizedUser);

    return normalizedUser;
  };

  const logout = async () => {
    try {
      /*
       * Client logout does not need
       * employee logout endpoint.
       */
      if (
        String(user?.role).toLowerCase() !==
        'client'
      ) {
        await api.post(
          '/auth/logout'
        );
      }
    } catch (error) {
      console.error(
        'LOGOUT ERROR:',
        error
      );
    } finally {
      localStorage.removeItem('token');
      localStorage.removeItem('user');

      setUser(null);
    }
  };

  return (
    <AuthContext.Provider
      value={{
        user,
        setUser,
        loading,
        login,
        logout,
      }}
    >
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => {
  const ctx = useContext(
    AuthContext
  );

  if (!ctx) {
    throw new Error(
      'useAuth must be used inside AuthProvider'
    );
  }

  return ctx;
};